/**
 * Type declarations for the buildsweep public API.
 *
 * Kept hand-written (rather than generated from JSDoc) so the published types
 * describe exactly the surface covered by semver, and so consumers do not need
 * the source to be compiled.
 */

import type { Dir } from "node:fs";

/**
 * How confident buildsweep is that a directory is disposable.
 *
 * - `safe`: regenerated by a standard build/install command (`node_modules`,
 *   `target`, `__pycache__`).
 * - `risky`: commonly disposable but can hold real content (`tmp`, `vendor`,
 *   `.vercel`). Excluded unless explicitly opted in.
 */
export type Risk = "safe" | "risky";

/** One ecosystem's worth of rules, e.g. everything Rust-related. */
export interface EcosystemRule {
  /** Human-readable name shown in reports, e.g. "Rust / Cargo". */
  label: string;
  risk: Risk;
  /**
   * Directory names to match. May contain a single `*` as a leading or
   * trailing wildcard, e.g. `"*.egg-info"`.
   */
  dirs: string[];
  /**
   * Only treat a match as real if a file in the same parent directory matches
   * one of these patterns. Disambiguates names claimed by several ecosystems,
   * such as `bin/` for both Go and .NET.
   */
  requireSibling?: string[];
  /** Free-form note for rule authors; not used by the scanner. */
  note?: string;
}

/** A complete rule set, as found in rules/default-rules.json or a user file. */
export interface RuleSet {
  /** Directory names never descended into, e.g. `.git`. */
  alwaysSkip?: string[];
  /** Keyed by ecosystem id, e.g. `rust`, `python`. */
  ecosystems: Record<string, EcosystemRule>;
}

/** A resolved rule as stored in the scanner's lookup table. */
export interface MatchEntry {
  /** Ecosystem id this rule came from, e.g. `rust`. */
  ecosystem: string;
  label: string;
  risk: Risk;
  requireSibling?: string[];
}

/** A {@link MatchEntry} whose directory name contains a wildcard. */
export interface PatternRule extends MatchEntry {
  pattern: string;
}

/** Flattened rules, shaped for cheap per-directory checks during the walk. */
export interface Lookup {
  alwaysSkip: Set<string>;
  /** Literal directory name to the rules claiming it. */
  exactNames: Map<string, MatchEntry[]>;
  patternRules: PatternRule[];
}

export interface BuildLookupOptions {
  /** Include rules marked `risky`. Defaults to falsy (excluded). */
  includeRisky?: boolean;
  /** If non-empty, restrict the scan to these ecosystem ids. */
  only?: string[] | null;
  /** Ecosystem ids to skip. */
  exclude?: string[] | null;
}

/** A directory the scanner identified as disposable. */
export interface Match {
  /** Absolute path to the matched directory. */
  path: string;
  /** Basename of the matched directory. */
  name: string;
  ecosystem: string;
  label: string;
  risk: Risk;
  /** Total size of the directory's contents. Absent when sizing is disabled. */
  sizeBytes?: number;
}

/** Periodic status while a scan is in flight. */
export interface ScanProgress {
  dirsVisited: number;
  matchesFound: number;
  /** Directory currently being walked. Absent during the sizing pass. */
  currentPath?: string;
  /** Directory currently being sized. Only set during the sizing pass. */
  sizing?: string;
}

export interface ScanOptions {
  /** Called at most once per `progressIntervalMs` during the walk. */
  onProgress?: ((update: ScanProgress) => void) | null;
  /** Minimum gap between progress callbacks. Defaults to 150. */
  progressIntervalMs?: number;
  /**
   * Compute `sizeBytes` for each match. Defaults to true. Disabling skips a
   * full second pass over matched trees, which is much faster on large roots.
   */
  computeSizes?: boolean;
}

export interface ScanResult {
  matches: Match[];
  /** Total directories considered, for reporting scan coverage. */
  dirsVisited: number;
}

export interface OpendirWithRetryOptions {
  /** Additional attempts after the first. Defaults to 4. */
  retries?: number;
  /** Base backoff, multiplied by the attempt number. Defaults to 25. */
  delayMs?: number;
  /** Injectable `opendir` implementation, for testing. */
  open?: (dirPath: string) => Promise<Dir>;
}

/** ANSI colour helpers. Each is a no-op when stdout is not a TTY, or when `NO_COLOR` is set. */
export interface Color {
  red: (text: string) => string;
  green: (text: string) => string;
  yellow: (text: string) => string;
  cyan: (text: string) => string;
  bold: (text: string) => string;
  dim: (text: string) => string;
}

/** Load a fresh, mutable copy of the rule set shipped with buildsweep. */
export declare function loadDefaultRules(): Promise<RuleSet>;

/**
 * Read a user rules file. Resolves to `null` if the file does not exist, and
 * rejects if it exists but cannot be read or parsed.
 */
export declare function loadUserRules(filePath: string): Promise<RuleSet | null>;

/**
 * Merge user rules over the defaults. Additive: `dirs` and `alwaysSkip` are
 * unioned, so a project can extend an ecosystem without redeclaring it.
 * Returns `defaultRules` unchanged when `userRules` is nullish.
 */
export declare function mergeRules(
  defaultRules: RuleSet,
  userRules?: RuleSet | null,
): RuleSet;

/** Flatten a rule set into the lookup structure {@link scanForMatches} expects. */
export declare function buildLookup(
  rules: RuleSet,
  options: BuildLookupOptions,
): Lookup;

/**
 * Walk `root` once, collecting directories that match `lookup`. Matched
 * directories are pruned, so their contents are never walked or reported as
 * nested matches. Unreadable directories are skipped rather than throwing.
 */
export declare function scanForMatches(
  root: string,
  lookup: Lookup,
  options?: ScanOptions,
): Promise<ScanResult>;

/**
 * `fs.opendir` with a short backoff on transient locking errors (`EBUSY`,
 * `EPERM`, `EMFILE`, `ENFILE`), which Windows raises for directories that are
 * readable moments later. Stable errors such as `ENOENT` are not retried.
 */
export declare function opendirWithRetry(
  dirPath: string,
  options?: OpendirWithRetryOptions,
): Promise<Dir>;

/**
 * Format a byte count as a human-readable string, e.g. `"1.4 GB"`.
 * Returns `"0 B"` for zero, negative, and non-finite input.
 */
export declare function formatBytes(bytes: number): string;

export declare const color: Color;

/**
 * Match a directory name against a rule pattern. Supports exact names and a
 * single leading or trailing `*`. Throws on patterns with more than one `*`.
 */
export declare function matchesPattern(name: string, pattern: string): boolean;

/** True if `name` matches any of `patterns`. See {@link matchesPattern}. */
export declare function matchesAny(name: string, patterns: string[]): boolean;

/**
 * Run the CLI with the given arguments (as in `process.argv.slice(2)`) and
 * resolve to the intended process exit code. Writes to stdout and may prompt
 * on stdin unless `--yes`, `--dry-run`, or `--json` is passed.
 */
export declare function run(argv: string[]): Promise<number>;
